### Vectors (Rank 1 Tensors) in NumPy

In [1]:
import numpy as np

In [2]:
x = np.array([25, 2, 5]) # type argument is optional, e.g.: dtype=np.float16
x

array([25,  2,  5])

In [3]:
len(x)

3

In [5]:
x.shape

(3,)

In [6]:
type(x)

numpy.ndarray

In [7]:
x[0]

25

In [8]:
type(x[0])

numpy.int64

### Vector Transposition

In [9]:
# Transposing a regular 1-D array has no effect.
x_t = x.T

In [10]:
x_t

array([25,  2,  5])

In [12]:
x.shape
# There is no second dimension to transform into so shape doesn't change.

(3,)

In [13]:
# Write it in nested bracket style so it has two dimensions to work with.
y = np.array([[25, 2, 5]])
y

array([[25,  2,  5]])

In [14]:
y.shape

(1, 3)

In [18]:
y_t = y.T
y_t

array([[25],
       [ 2],
       [ 5]])

### Zero Vectors
The vectors in which every scalar is $0$.

In [22]:
z = np.array([np.zeros(3)])
z

array([[0., 0., 0.]])

### Vectors in PyTorch & TensorFlow

In [25]:
import torch
import tensorflow as tf

In [31]:
x_pt = torch.tensor([[25, 2, 5]])
x_pt

tensor([[25,  2,  5]])

In [34]:
x_tf = tf.Variable([[25, 2, 5]])
x_tf

<tf.Variable 'Variable:0' shape=(1, 3) dtype=int32, numpy=array([[25,  2,  5]], dtype=int32)>

In [36]:
x_pt.T

tensor([[25],
        [ 2],
        [ 5]])

In [39]:
tf.transpose(x_tf)

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[25],
       [ 2],
       [ 5]], dtype=int32)>