In [8]:
import numpy as np


# Scalar code example.
s = 5

# Vector code example.
v = np.array([1, 2, 3, 4])

In [9]:
print("Scaler code: ",s)
print("Vector code: ", v)

Scaler code:  5
Vector code:  [1 2 3 4]


In [12]:
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Matrix code: ", m)

Matrix code:  [[1 2 3]
 [4 5 6]
 [7 8 9]]


## Matrix Addition

In matrix addition, corresponding matrix entries are added together.

In [13]:
a = np.array([[3, 8], [4, 6]])
b = np.array([[4, 0], [1, -9]])

print(a)
print(b)

[[3 8]
 [4 6]]
[[ 4  0]
 [ 1 -9]]


In [14]:
a + b

array([[ 7,  8],
       [ 5, -3]])

## Matrix Multiplication

- In matrix multiplication, the number of rows the first matrix must be equal to the number of columns of the second matrix.
- The dot product between each row and column of the matrix and placed as an entry into the resulting matrix as shown in the formula below.

In [19]:
mx1 = np.array([[1, 2, 3], [4, 5, 6]])
mx2 = np.array([[7, 8], [9, 10], [11, 12]])

print(mx1)
print(mx2)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]


In [29]:
np.dot(mx1, mx2)

array([[ 58,  64],
       [139, 154]])

## Identity Matrix

- The identity matrix is a square matrix of elements equal to 0 except for the elements along the diagonal that are all equal to 1.

In [33]:
ax1 = np.array([[4, 3, -2], [-3, 0, 6], [1, 2, 8]])
ax2 = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])

print(ax1)
print(ax2)

[[ 4  3 -2]
 [-3  0  6]
 [ 1  2  8]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [34]:
np.dot(ax1, ax2)

array([[ 4,  3, -2],
       [-3,  0,  6],
       [ 1,  2,  8]])