## Matrices (Rank 2 Tensors)

#### $$\begin{bmatrix}
x_{1,1} & x_{1,2}\\ 
x_{2,1} & x_{2,2}\\
x_{3,1} & x_{3,2}\\
\end{bmatrix}$$

- Two dimensional array of number.
- Denoted in UPPER, _italic_, __bold__, eg: ___X___
- Height is given priority ahead of width in notation. i.e: $[X_{row}, X_{col}]$
  - If ___X___ has three row & two columns, the shape is ___(3, 2)___
- Colon $(:)$ represents an entire row or column.
  - Left column of matrix ___X___ is $X_{:,1}$
  - Middle column of matrix ___X___ is $X_{2,:}$ 

In [25]:
import numpy as np
import torch
import tensorflow as tf

2023-06-29 11:41:23.366449: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [2]:
# Use array() with nested brackets.
X = np.array([ [25, 2], [5, 26], [3, 7] ])
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [3]:
X.shape

(3, 2)

In [4]:
X.size

6

#### Select Left column of matrix X (zero-indexed)

In [24]:
X[1:2]

array([[ 5, 26]])

### Matriced in PyTorch

In [26]:
X_pt = torch.tensor([ [25, 2], [5, 26], [3, 7] ])
X_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [27]:
X_pt.shape

torch.Size([3, 2])

In [43]:
X_pt[0, 0]

tensor(25)

### Matrices in TensorFlow

In [44]:
X_tf = tf.Variable([[ 25, 2 ], [5, 26], [3, 7]])

In [45]:
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 5, 26],
       [ 3,  7]], dtype=int32)>

In [46]:
tf.rank(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [47]:
tf.shape(X_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>

In [52]:
X_tf[1, 0]

<tf.Tensor: shape=(), dtype=int32, numpy=5>