## $L^{2}$ Norm
- The most common norm
- Measures simple ___(Euclidean)___ distance from the origin.

### $$||x||_{2} = \sqrt{\Sigma_{i} x_{i}^{2}}$$

In [2]:
import numpy as np

In [3]:
x = np.array([25, 2, 5])

In [6]:
np.linalg.norm(x)

25.573423705088842

## $L^{1}$ Norm
- Another common norm in ML.
- Varies linearly at all locations whether near or far from the origin.
- Used when the difference between zero & non-zero is key.
 ### $$||x||_{1} = \Sigma_{i} |x_{i}|$$

In [7]:
x

array([25,  2,  5])

In [8]:
total = 0
for i in range(len(x)):
    total += np.abs(x[i])
total

32

## Squared $L^{2}$ Norm
- Computationally cheaper to use than $L^{2}$ norm because:
  - Squared $L^{2}$ norm equals to simply $x^{T}x$
  - Derivatives (Used to train many ML Algorithms) of element $x$ require that element (scalar) alone,
    where as $L^{2}$ norm requires $x$ vector.
- Downside is it grows slowly near the origin so it can be used if distinguishing between $0$ and $non-zero$ is the key.

###  $$||x||_{2}^{2} = \Sigma_{i} x_{i}^{2}$$

In [10]:
x

array([25,  2,  5])

In [11]:
np.dot(x, x)

654

## Max Norm

- Occurs frequently in ML
- Returns the absolute value of the largest-magnitude element.

### $$||x||_{\infty} = max_{i} |x_{i}|$$

In [12]:
x

array([25,  2,  5])

In [13]:
np.max([np.abs(x[0]), np.abs(x[1]), np.abs(x[2])])

25

## Generalized L^{P} Norm

- $p$ must be:
  - A real number
  - Greater than or equal to one.
- Can derive $L_{1}$, $L_{2}$, $L_{\infty}$ formulae by substituting for $p$.
- Norms, particularly $L_{1}$ and $L_{2}$ used to regularize objective functions.
 
### $$||x||_{p} = (\Sigma_{i} |x_{i}|^{p})^{\frac{1}{p}}$$

## Visualizing Norms